# =============================================================
# ALPHA HEMS: ESP32 AUTONOMICZNY RDZEŃ v6.18 (LILYGO SD)
# Zmiany:
# - v6.18: Zmiana nazwy AP i nadanie prostego hasła w celu ominięcia
#   problemu z cache'owaniem profilu sieci w systemach iOS/Android.
# =============================================================

substitutions:
  name: "alpha-ems-s3"
  friendly_name: "Alpha EMS Core"
  modbus_inverter_address: "0x01"
  safe_mode_delay: 600s
  default_maximum_battery_charge_current: "100"
  default_max_sell_power: "12000"
  default_system_work_mode: "Zero Export To Load"
  default_solar_sell: "on"
  default_force_off_grid: "off"
  enable_sync_time: "false"
  api_key: "QUxBMU1BMUtPVEExQTFLT1QxTUExQUxFMTY5MTY5MTE="

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  includes:
    - sd_logger.h
  libraries:
    - "FS"
    - "SD"
    - "SPI"
  on_boot:
    priority: 600
    then:
      - lambda: |-
          sd_logger.setup();

esp32:
  board: esp32dev
  framework:
    type: arduino
    advanced:
      sram1_as_iram: true

# ==========================================
# 1. SIEĆ, BLUETOOTH I PROVISIONING
# ==========================================
wifi:
  ap:
    ssid: "Alpha HEMS Setup"
    password: "12345678"

captive_portal:

improv_serial:

esp32_improv:
  authorizer: none

api:
  reboot_timeout: 0s

# ==========================================
# 0. MAGISTRALA SPI (Sprzętowa podstawa pod SD)
# ==========================================
