# =============================================================
# ALPHA HEMS: ESP32 AUTONOMICZNY RDZEŃ v7.02 (WAVESHARE S3 - GITHUB)
# Zmiany:
# - v7.02: Migracja pliku bazowego pod architekturę ESP32-S3 (SKU 28117).
#   Aktywacja 8MB PSRAM, usunięcie obsługi SD/SPI, powrót Web Servera.
# =============================================================

substitutions:
  name: "alpha-ems-s3"
  friendly_name: "Alpha EMS Core"
  modbus_inverter_address: "0x01"
  safe_mode_delay: 600s
  default_maximum_battery_charge_current: "100"
  default_max_sell_power: "12000"
  default_system_work_mode: "Zero Export To Load"
  default_solar_sell: "on"
  default_force_off_grid: "off"
  enable_sync_time: "false"
  api_key: "QUxBMU1BMUtPVEExQTFLT1QxTUExQUxFMTY5MTY5MTE="
  wifi_ssid: "WIFI_CONFIG"
  wifi_password: "WIFI_CONFIG"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# ==========================================
# AKTYWACJA 8MB PSRAM (Sprzętowy ratunek)
# ==========================================
psram:
  mode: octal
  speed: 80MHz

# ==========================================
# 1. SIEĆ I PROVISIONING
# ==========================================
wifi:
  ap:
    ssid: "Alpha HEMS Setup"
    password: "12345678"

captive_portal:

logger:

improv_serial:

api:
  reboot_timeout: 0s

web_server:
  port: 80

# ==========================================
# UWAGA: USUNIĘTO SEKCJĘ "0. MAGISTRALA SPI" 
# ==========================================
